name: Go binary sender release
#
env:
  ACTIONS_STEP_DEBUG: true
#
on:
  release:
    types: [published]
#
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    #
    steps:
    - uses: actions/checkout@v3
    #
    - name: Setup Go 
      uses: actions/setup-go@v5
      with:
        go-version: 1.18
        cache: true
    #
    - name: Build receiver binary
      id: build-sender-binary
      shell: bash
      run: |
          sudo sh build-receiver.sh 
    #
    - name: Upload sender-binary #${{ matrix.go-version }}
      uses: actions/upload-artifact@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        name: upload-sender-binary
        path: /tmp/bin/sender-binary.tar.gz
    #
    - name: Release sender-binary
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: "# Release ${{github.ref}} \n"
        files: |
          LICENSE
          /tmp/bin/sender-binary.tar.gz